Document: fotoshare
Title: Debian fotoshare Manual
Author: <insert document author here>
Abstract: This manual describes what fotoshare is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fotoshare/fotoshare.sgml.gz

Format: postscript
Files: /usr/share/doc/fotoshare/fotoshare.ps.gz

Format: text
Files: /usr/share/doc/fotoshare/fotoshare.text.gz

Format: HTML
Index: /usr/share/doc/fotoshare/html/index.html
Files: /usr/share/doc/fotoshare/html/*.html
